### ISSUE TITLE
 switch build to Qt5

### ISSUE THREAD

**Issue by sergiomb2** [UnitedRPMs/smplayer#1]
Hi, 

@kuboosoft  , where is mageia diffs or patches ? (I want update it on RPMFusion) 

from https://pkgs.org/mageia-cauldron/mageia-core-release-x86_64/smplayer-16.4.0-1.mga6.x86_64.rpm.html

2016-03-29 - daviddavid<daviddavid> 16.4.0-1.mga6
- Revision: 996375
- new version: 16.4.0

2016-01-15 - daviddavid<daviddavid> 16.1.0-1.mga6
- Revision: 923335
- new version: 16.1.0

2015-12-02 - daviddavid<daviddavid> 15.11.0-1.mga6
- Revision: 907602
- new version: 15.11.0

2015-11-12 - daviddavid<daviddavid> 15.9.0-1.mga6
- Revision: 902800
- new version: 15.9.0
- switch build to Qt5
- update file list

**Comment by sergiomb2** [comment]
https://pkgs.rpmfusion.org/cgit/free/smplayer.git/commit/?id=e7664fa464b1e90c32f377870dec5a5ef080be99

done !

**Comment by sergiomb2** [comment]
now I understood you'd like use mageia organization

**Comment by kuboosoft** [comment]
@sergiomb2 hey!! check the commits, who made, uploaded, updated or patched smplayer is @paulcarroty . I wash my hands like Pontius Pilatus hahaha. I recently updated it... :)

**Comment by sergiomb2** [comment]
I'm the package maintainer of smplayer in rpmfusion ... , but this issue have one year 17 Jul 2016

**Comment by kuboosoft** [comment]
> @kuboosoft , where is mageia diffs or patches ? (I want update it on RPMFusion)


I am checking issues... sorry very late (I never saw it) ;)

**Comment by sergiomb2** [comment]
```
mgarepo co smplayer
git clone git@github.com:UnitedRPMs/smplayer.git smplayer.unitedrpms
rfpkg clone free/smplayer

diff smplayer.spec ../ -upw | vi -R - 
```
I saw that smplayer.spec of rf and uni is the same but uni is a little older , mageia version is a little different because have mageia syntax and more outdated but what we should do ? delete _or_ copy rf version to here ?

**Comment by kuboosoft** [comment]
@sergiomb2 remembers @paulcarroty [put smplayer in urpms](https://github.com/UnitedRPMs/smplayer/blob/master/smplayer.spec#L211), I only updated (2 current versions, without major changes). if it has the same structure of [rf](https://github.com/UnitedRPMs/smplayer/blob/master/smplayer.spec#L214) not matter as mag... the question is ¿The people are using it? if urpms has smplayer,Then smplayer is also maintained by unitedrpms, and  we must maintain it.

**Comment by sergiomb2** [comment]
(*)  delete _or_ copy rf version to here ?  you choose copy ?

**Comment by kuboosoft** [comment]
@sergiomb2 no matter ( the important is a version of smplayer here); the ethic is respects the changelog (I don't made changes here only update the version, then green light) :) .

Relationated, There are people inventing fool things... I recently had an altercation with a silly and lying ambassador (bad for FAMLATAM). 
Imagine, We are devoting our time to the project, without any benefit, and still dares to break my balls.
